# Generated by Django 2.1.5 on 2019-02-12 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ecslist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=70)),
                ('cpu', models.CharField(max_length=10)),
                ('mem', models.CharField(max_length=10)),
                ('inst_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=20)),
                ('pro_platform', models.CharField(max_length=20)),
                ('pro_conf', models.CharField(max_length=100)),
                ('pro_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='ecslist',
            name='ecs_project',
            field=models.ManyToManyField(to='cmdb.project'),
        ),
    ]
