# Generated by Django 2.1.7 on 2019-02-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0005_auto_20190214_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pro_conf',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='pro_name',
            field=models.CharField(max_length=100),
        ),
    ]
