# Generated by Django 2.1.7 on 2019-02-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0006_auto_20190216_0823'),
    ]

    operations = [
        migrations.CreateModel(
            name='urlinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.CharField(max_length=100)),
                ('project', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=500)),
                ('urlinfo', models.CharField(max_length=100)),
                ('respone_code', models.CharField(max_length=50)),
                ('respone_data', models.CharField(max_length=500)),
            ],
        ),
    ]
