# Generated by Django 2.1.7 on 2019-02-21 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0007_urlinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlinfo',
            name='respone_code',
        ),
        migrations.RemoveField(
            model_name='urlinfo',
            name='respone_data',
        ),
    ]
