# Generated by Django 2.1.5 on 2019-02-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('user', models.CharField(max_length=20)),
                ('cmd', models.CharField(max_length=100)),
                ('stdout', models.CharField(max_length=200)),
            ],
        ),
    ]
