# Generated by Django 2.1.7 on 2019-02-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_redis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='redismessage',
            name='password',
            field=models.CharField(default='', max_length=200),
        ),
    ]
